function [methodinfo,structs,enuminfo,ThunkLibName]=mproto
%MPROTO Create structures to define interfaces found in 'Header'.

%This function was generated by loadlibrary.m parser version  on Wed Oct 12 15:46:59 2016
%perl options:'Header.i -outfile=mproto.m -thunkfile=MatlabAsyncKeys_thunk_pcwin64.c -header=Header.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'MatlabAsyncKeys_thunk_pcwin64');
%  int keyinfo (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='keyinfo'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
methodinfo=fcns;